
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jan 17 19:48:25 CET 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LTE = 34;
  public static final int LBRACKET = 38;
  public static final int CONST = 25;
  public static final int CONTINUE = 35;
  public static final int LPAREN = 6;
  public static final int SEMI = 5;
  public static final int MINUS = 21;
  public static final int CHARACTER = 55;
  public static final int RPAREN = 7;
  public static final int AND = 26;
  public static final int LT = 27;
  public static final int OR = 36;
  public static final int COMMA = 8;
  public static final int ORD = 50;
  public static final int CLASS = 33;
  public static final int INC = 24;
  public static final int DIV = 20;
  public static final int DOUBLEDOT = 16;
  public static final int EOL = 47;
  public static final int PLUS = 11;
  public static final int IF = 56;
  public static final int ASSIGN = 12;
  public static final int DOT = 19;
  public static final int BOOLEAN = 52;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int EQUAL = 45;
  public static final int RBRACKET = 39;
  public static final int LAMBDA = 46;
  public static final int NEW = 18;
  public static final int error = 1;
  public static final int MUL = 43;
  public static final int ISNULL = 15;
  public static final int NUMBER = 53;
  public static final int MOD = 42;
  public static final int NEQ = 30;
  public static final int IDENT = 54;
  public static final int BREAK = 44;
  public static final int VOID = 13;
  public static final int GTE = 40;
  public static final int SWITCH = 23;
  public static final int FOREACH = 37;
  public static final int COLON = 14;
  public static final int ELSE = 57;
  public static final int LBRACE = 3;
  public static final int ENUM = 41;
  public static final int READ = 28;
  public static final int GOTO = 51;
  public static final int WHILE = 31;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 17;
  public static final int PROG = 2;
  public static final int LEN = 48;
  public static final int CHR = 49;
  public static final int DEC = 22;
  public static final int GT = 29;
  public static final int PRINT = 9;
  public static final int DO = 32;
}

