# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\generisi_kljuc_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GenerisiKljucDialog(object):
    def setupUi(self, GenerisiKljucDialog):
        GenerisiKljucDialog.setObjectName("GenerisiKljucDialog")
        GenerisiKljucDialog.resize(326, 172)
        self.layoutWidget = QtWidgets.QWidget(GenerisiKljucDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 11, 293, 154))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineSifra = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineSifra.setObjectName("lineSifra")
        self.gridLayout.addWidget(self.lineSifra, 4, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.cbVelicinaKljuca = QtWidgets.QComboBox(self.layoutWidget)
        self.cbVelicinaKljuca.setObjectName("cbVelicinaKljuca")
        self.cbVelicinaKljuca.addItem("")
        self.cbVelicinaKljuca.addItem("")
        self.gridLayout.addWidget(self.cbVelicinaKljuca, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineMejl = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineMejl.setObjectName("lineMejl")
        self.gridLayout.addWidget(self.lineMejl, 1, 1, 1, 1)
        self.cbAlgoritam = QtWidgets.QComboBox(self.layoutWidget)
        self.cbAlgoritam.setObjectName("cbAlgoritam")
        self.cbAlgoritam.addItem("")
        self.cbAlgoritam.addItem("")
        self.gridLayout.addWidget(self.cbAlgoritam, 3, 1, 1, 1)
        self.lineIme = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineIme.setObjectName("lineIme")
        self.gridLayout.addWidget(self.lineIme, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.layoutWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)

        self.retranslateUi(GenerisiKljucDialog)
        QtCore.QMetaObject.connectSlotsByName(GenerisiKljucDialog)

    def retranslateUi(self, GenerisiKljucDialog):
        _translate = QtCore.QCoreApplication.translate
        GenerisiKljucDialog.setWindowTitle(_translate("GenerisiKljucDialog", "Generisi kljuc"))
        self.label_3.setText(_translate("GenerisiKljucDialog", "Velicina kljuca:"))
        self.label.setText(_translate("GenerisiKljucDialog", "Ime:"))
        self.label_5.setText(_translate("GenerisiKljucDialog", "Sifra:"))
        self.cbVelicinaKljuca.setItemText(0, _translate("GenerisiKljucDialog", "1024"))
        self.cbVelicinaKljuca.setItemText(1, _translate("GenerisiKljucDialog", "2048"))
        self.label_2.setText(_translate("GenerisiKljucDialog", "Mejl:"))
        self.cbAlgoritam.setItemText(0, _translate("GenerisiKljucDialog", "RSA"))
        self.cbAlgoritam.setItemText(1, _translate("GenerisiKljucDialog", "DSA/El Gamal"))
        self.label_4.setText(_translate("GenerisiKljucDialog", "Algoritam:"))
