# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\uvezi_kljuc.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UveziKljucDialog(object):
    def setupUi(self, UveziKljucDialog):
        UveziKljucDialog.setObjectName("UveziKljucDialog")
        UveziKljucDialog.resize(400, 114)
        self.buttonBox = QtWidgets.QDialogButtonBox(UveziKljucDialog)
        self.buttonBox.setGeometry(QtCore.QRect(290, 20, 81, 241))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.widget = QtWidgets.QWidget(UveziKljucDialog)
        self.widget.setGeometry(QtCore.QRect(10, 20, 271, 74))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.leIme = QtWidgets.QLineEdit(self.widget)
        self.leIme.setObjectName("leIme")
        self.gridLayout.addWidget(self.leIme, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.leMejl = QtWidgets.QLineEdit(self.widget)
        self.leMejl.setObjectName("leMejl")
        self.gridLayout.addWidget(self.leMejl, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.leLozinka = QtWidgets.QLineEdit(self.widget)
        self.leLozinka.setObjectName("leLozinka")
        self.gridLayout.addWidget(self.leLozinka, 2, 1, 1, 1)

        self.retranslateUi(UveziKljucDialog)
        QtCore.QMetaObject.connectSlotsByName(UveziKljucDialog)

    def retranslateUi(self, UveziKljucDialog):
        _translate = QtCore.QCoreApplication.translate
        UveziKljucDialog.setWindowTitle(_translate("UveziKljucDialog", "Uvoz kljuca"))
        self.label.setText(_translate("UveziKljucDialog", "Ime:"))
        self.label_2.setText(_translate("UveziKljucDialog", "Mejl:"))
        self.label_3.setText(_translate("UveziKljucDialog", "Lozinka:"))
